# Generated by Django 4.2.7 on 2025-12-16 17:21

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#8B4513', help_text='Hex color code for calendar display', max_length=20, verbose_name='Calendar Color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon Class')),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TraditionalFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Festival Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('history', models.TextField(blank=True, verbose_name='History & Significance')),
                ('typical_month', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Month when this festival typically occurs', null=True, verbose_name='Typical Month')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Duration (Days)')),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
                ('activities', models.TextField(blank=True, verbose_name='Activities & Rituals')),
                ('traditional_attire', models.TextField(blank=True, verbose_name='Traditional Attire')),
                ('food_and_drinks', models.TextField(blank=True, verbose_name='Traditional Food & Drinks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Still Celebrated')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Festival')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Traditional Festival',
                'verbose_name_plural': 'Traditional Festivals',
                'ordering': ['typical_month', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.TextField(blank=True, max_length=300, verbose_name='Short Description')),
                ('event_type', models.CharField(choices=[('festival', 'Traditional Festival'), ('ceremony', 'Ceremony'), ('meeting', 'Palace Meeting'), ('celebration', 'Celebration'), ('memorial', 'Memorial'), ('official', 'Official Event'), ('community', 'Community Event'), ('other', 'Other')], default='other', max_length=20, verbose_name='Event Type')),
                ('start_date', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='All Day Event')),
                ('recurrence', models.CharField(choices=[('none', 'One-time Event'), ('annual', 'Annual'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], default='none', max_length=10, verbose_name='Recurrence')),
                ('venue', models.CharField(max_length=200, verbose_name='Venue')),
                ('address', models.TextField(blank=True, verbose_name='Full Address')),
                ('map_url', models.URLField(blank=True, verbose_name='Map URL')),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
                ('dress_code', models.CharField(blank=True, max_length=200, verbose_name='Dress Code')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Special Instructions')),
                ('contact_info', models.TextField(blank=True, verbose_name='Contact Information')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Event')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date'],
            },
        ),
    ]
