# Generated by Django 4.2.7 on 2025-12-16 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Author Name')),
                ('author_title', models.CharField(blank=True, help_text='E.g., Community Leader, Elder, etc.', max_length=100, verbose_name='Title/Position')),
                ('author_location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('content', models.TextField(max_length=1000, verbose_name='Feedback Content')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Feedback',
                'verbose_name_plural': 'Public Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village/Community')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('subject', models.CharField(max_length=300, verbose_name='Subject')),
                ('message_type', models.CharField(choices=[('general', 'General Inquiry'), ('request', 'Request/Appeal'), ('feedback', 'Feedback'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('media', 'Media/Press Inquiry'), ('other', 'Other')], default='general', max_length=20, verbose_name='Message Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('is_responded', models.BooleanField(default=False, verbose_name='Responded')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal'), ('low', 'Low Priority')], default='normal', max_length=10, verbose_name='Priority')),
                ('response', models.TextField(blank=True, verbose_name='Response')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
