# Generated by Django 4.2.7 on 2025-12-16 17:21

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile Image')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('role', models.CharField(choices=[('ejeh', 'Ejeh (Traditional Ruler)'), ('palace_admin', 'Palace Administrator'), ('chief', 'Council of Chiefs'), ('member', 'Community Member'), ('visitor', 'Public Visitor')], default='visitor', max_length=20, verbose_name='Role')),
                ('traditional_title', models.CharField(blank=True, help_text='E.g., Chief, Elder, etc.', max_length=100, verbose_name='Traditional Title')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village/Community')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Ward')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Member')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ChiefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Chieftaincy Title')),
                ('domain', models.CharField(blank=True, max_length=200, verbose_name='Domain/Area of Authority')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Chief')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chief_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chief Profile',
                'verbose_name_plural': 'Chief Profiles',
                'ordering': ['order', 'title'],
            },
        ),
    ]
