# Generated by Django 4.2.7 on 2025-12-16 17:21

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class (primary, success, warning, danger, info)', max_length=20, verbose_name='Badge Color')),
            ],
            options={
                'verbose_name': 'Announcement Category',
                'verbose_name_plural': 'Announcement Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoyalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('signature_name', models.CharField(default='His Royal Majesty, The Ejeh of Ankpa', max_length=200, verbose_name='Signature Name')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('message_date', models.DateField(verbose_name='Message Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Royal Message',
                'verbose_name_plural': 'Royal Messages',
                'ordering': ['-message_date'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Excerpt')),
                ('content', models.TextField(verbose_name='Content')),
                ('announcement_type', models.CharField(choices=[('royal_message', 'Royal Message from Ejeh'), ('official', 'Official Announcement'), ('communique', 'Communiqué'), ('press_release', 'Press Release'), ('notice', 'Public Notice'), ('event', 'Event Announcement')], default='official', max_length=20, verbose_name='Announcement Type')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High Priority'), ('normal', 'Normal'), ('low', 'Low Priority')], default='normal', max_length=10, verbose_name='Priority')),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Attachment (PDF)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pinned (Always Show First)')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Publish Date')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.announcementcategory')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_pinned', '-publish_date', '-created_at'],
            },
        ),
    ]
