# Generated by Django 4.2.7 on 2025-12-16 17:21

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjehProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('title', models.CharField(default='His Royal Majesty', max_length=100, verbose_name='Royal Title')),
                ('reign_status', models.CharField(choices=[('present', 'Present Ejeh'), ('past', 'Past Ejeh')], default='past', max_length=10, verbose_name='Reign Status')),
                ('official_portrait', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Official Portrait')),
                ('coronation_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Coronation Image')),
                ('reign_start', models.DateField(blank=True, null=True, verbose_name='Reign Start Date')),
                ('reign_end', models.DateField(blank=True, null=True, verbose_name='Reign End Date')),
                ('reign_number', models.PositiveIntegerField(blank=True, help_text='Order in succession (e.g., 1st, 2nd, etc.)', null=True, verbose_name='Reign Number')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('early_life', models.TextField(blank=True, verbose_name='Early Life')),
                ('achievements', models.TextField(blank=True, verbose_name='Achievements & Contributions')),
                ('legacy', models.TextField(blank=True, verbose_name='Legacy')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='Place of Birth')),
                ('education', models.TextField(blank=True, verbose_name='Education')),
                ('occupation_before_throne', models.TextField(blank=True, help_text='Professional career before ascending the throne', verbose_name='Occupation Before Throne')),
                ('full_title_and_honours', models.TextField(blank=True, help_text='Complete list of royal titles and honours', verbose_name='Full Title and Honours')),
                ('royal_title', models.CharField(blank=True, help_text='E.g., Ejeh Ankpa IV', max_length=100, verbose_name='Royal Title Name')),
                ('motto', models.TextField(blank=True, verbose_name='Royal Motto')),
                ('hobbies', models.TextField(blank=True, verbose_name='Hobbies & Interests')),
                ('countries_visited', models.TextField(blank=True, verbose_name='Countries Visited')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Profile')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Ejeh Profile',
                'verbose_name_plural': 'Ejeh Profiles',
                'ordering': ['-reign_status', 'display_order', '-reign_start'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-crown)', max_length=50, verbose_name='Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Excerpt')),
                ('content', models.TextField(verbose_name='Content')),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('article_type', models.CharField(choices=[('history', 'Kingdom History'), ('tradition', 'Traditional Practices'), ('culture', 'Cultural Heritage'), ('title', 'Traditional Titles'), ('festival', 'Festivals'), ('language', 'Language & Arts')], default='history', max_length=20, verbose_name='Article Type')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'History & Culture Article',
                'verbose_name_plural': 'History & Culture Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PalaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palace_name', models.CharField(default='Ejeh Ankpa Palace', max_length=200, verbose_name='Palace Name')),
                ('tagline', models.CharField(default='The Traditional Institution of the Ejeh of Ankpa', max_length=300, verbose_name='Tagline')),
                ('about', models.TextField(blank=True, verbose_name='About the Palace')),
                ('mission', models.TextField(blank=True, verbose_name='Mission Statement')),
                ('vision', models.TextField(blank=True, verbose_name='Vision Statement')),
                ('address', models.TextField(blank=True, verbose_name='Palace Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Palace Logo')),
                ('banner_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Banner Image')),
                ('favicon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Favicon')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name': 'Palace Information',
                'verbose_name_plural': 'Palace Information',
            },
        ),
        migrations.CreateModel(
            name='TraditionalTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100, verbose_name='Title Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('hierarchy_level', models.PositiveIntegerField(help_text='1 = Highest (Ejeh), higher numbers = lower in hierarchy', verbose_name='Hierarchy Level')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Responsibilities')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements for Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Title')),
            ],
            options={
                'verbose_name': 'Traditional Title',
                'verbose_name_plural': 'Traditional Titles',
                'ordering': ['hierarchy_level', 'title_name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Thumbnail')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('occasion_type', models.CharField(choices=[('coronation', 'Coronation'), ('festival', 'Festival & Ceremony'), ('palace', 'Palace Occasion'), ('community', 'Community Event'), ('official', 'Official Visit'), ('cultural', 'Cultural Event'), ('other', 'Other')], default='other', max_length=20, verbose_name='Occasion Type')),
                ('date_taken', models.DateField(blank=True, null=True, verbose_name='Date Taken')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('photographer', models.CharField(blank=True, max_length=100, verbose_name='Photographer')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='palace.gallerycategory')),
                ('related_ejeh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='palace.ejehprofile')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-date_taken', '-created_at'],
            },
        ),
    ]
